/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface Backdrop {

    }
  }

  interface HTMLBackdropElement extends StencilComponents.Backdrop, HTMLStencilElement {}

  var HTMLBackdropElement: {
    prototype: HTMLBackdropElement;
    new (): HTMLBackdropElement;
  };
  interface HTMLElementTagNameMap {
    'backdrop': HTMLBackdropElement;
  }
  interface ElementTagNameMap {
    'backdrop': HTMLBackdropElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'backdrop': JSXElements.BackdropAttributes;
    }
  }
  namespace JSXElements {
    export interface BackdropAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface Modal {

    }
  }

  interface HTMLModalElement extends StencilComponents.Modal, HTMLStencilElement {}

  var HTMLModalElement: {
    prototype: HTMLModalElement;
    new (): HTMLModalElement;
  };
  interface HTMLElementTagNameMap {
    'modal': HTMLModalElement;
  }
  interface ElementTagNameMap {
    'modal': HTMLModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'modal': JSXElements.ModalAttributes;
    }
  }
  namespace JSXElements {
    export interface ModalAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyComponent {
      'first': string;
      'last': string;
    }
  }

  interface HTMLMyComponentElement extends StencilComponents.MyComponent, HTMLStencilElement {}

  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-component': JSXElements.MyComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;